#!/bin/bash
#Création le 08/05/2015 -- https://github.com/Maeda1/boinc
#v1.1-alpha

#But : suspend les UT d'un projet au choix qui sont sur le point de se terminer

#A CHANGER : dossier de travail de Boinc
boincdos="/media/Calculs/boinc"

#initialisation
ok=0
myself="$(readlink -f $0)"
mydir="${myself%/*}"
eval mydir=$mydir

#Vérifications CONF
if [ ! -d "$boincdos" ];then
	echo "Problème de paramétrage de la variable boincdos, éditer le script et mettre boincdos avec le chemin ou Boinc est installé !"
	exit 1
fi

testcmd=($(boinccmd --get_tasks | grep -e "fraction done:"  | grep -m 1 -o '[0-9]*\.[0-9]*'))
if [ -z $testcmd ];then
	echo "Problème avec la commande de vérification de la progression des tâches, si vous utilisez un client Boinc ancien, essayez la version v1.0 de suspend_calc ou mettez à jour Boinc"
	exit 2
fi

testcmd=($(boinccmd --get_tasks | grep -m 1 "   WU name: " | cut -d " " -f6))
if [ -z $testcmd ];then
	echo "Problème avec la commande de vérification de la progression des tâches, si vous utilisez un client Boinc ancien, essayez la version v1.0 de suspend_calc ou mettez à jour Boinc"
	exit 3
fi
if [ -z $testcmd ];then
	echo "Problème avec la commande de vérification du nom des tâches, si vous utilisez un client Boinc ancien, essayez la version v1.0 de suspend_calc ou mettez à jour Boinc"
	exit 2
fi
if [ ! -f "$mydir/suspend_calc_conf" ];then
	echo "Pas de fichier de configuration !"
	touch "$mydir/suspend_calc_conf"
	if [ $? -ne 0 ];then
		echo "Problème à la création du fichier suspend_calc_conf sous $mydir. Merci de le créer et relancer le script"
		exit 1
	fi
	echo "#url projet;temps restants limite en secondes" >> "$mydir/suspend_calc_conf"
	echo "default;60" >> "$mydir/suspend_calc_conf"
	if [ $? -ne 0 ];then
		echo "Problème pour écrire dans le fichier suspend_calc_conf sous $mydir. Merci de corriger, puis supprimer le fichier et relancer le script"
		exit 1
	fi
	echo "INFO : Fichier suspend_calc_conf créé au même niveau que suspend_calc. Configuration par défaut : 60 secondes. Modifiez-le pour y mettre vos préférences."
fi

#Recherche d'un argument précisant déjà l'URL du projet, si trouvé = pas de question posée
for arg in "$@"
do
        if [ "$(echo $arg | grep "^http")" ];then
                url_prj="$arg"
		break
        fi
done

#Choix projet
if [ -z $url_prj ];then
	while [ "$ok" != "OK" ]
	do
		echo "> Choix du projet cible <"
		boinccmd --get_project_status | grep -A 1 "\-----------" | more
		echo "> Entrer le choix voulu par le nombre correspondant < (0=quitter)"
		read chx_prj
		if [ $chx_prj = 0 ];then
			exit
		fi
		if [ "$(boinccmd --get_project_status | grep -A 1 "^$chx_prj) ")" = "" ];then
			echo "Erreur de saisie, ce choix n'existe pas"
			sleep 2
		else
			echo "============="
			echo "Votre choix :"
			echo "$(boinccmd --get_project_status | grep -A 1 "^$chx_prj) ")"
			url_prj="$(boinccmd --get_project_status | grep -A 2 "^$chx_prj) " | grep URL | cut -d " " -f6)"
			echo "============="
			echo "Est-ce OK pour démarrer ? (taper OK)"
			read ok
		fi
	done
fi

#Récupération temps limite du fichier préférences CONF
limite=$(grep -m1 "^$url_prj" "$mydir/suspend_calc_conf" | cut -d ";" -f2)
if [ -z $limite ];then
	limite=$(grep "default" "$mydir/suspend_calc_conf" | cut -d ";" -f2)
	echo "Pas de préférences trouvées : limite mise à $limite"
else
	echo "Préférence trouvée : limite mise à $limite"
fi

#Seuil de suspension limite en fonction du temps restant en fonction des projets
#Chaine commune à tous
#chcom="estimated CPU time remaining: "
#case "$url_prj" in
#	http://pogs.theskynet.org/pogs/)
#        	limite="1699s"
#		form="$chcom[1][0-6][0-9][0-9]\.|$chcom[0-9][0-9][0-9]\.|$chcom[0-9][0-9]\.|$chcom[0-9]\." ;;
#	http://boinc.bakerlab.org/rosetta/)
#        	limite="15599s"
#		form="$chcom[1][0-5][0-5][0-9][0-9]\.|$chcom[0-9][0-9][0-9][0-9]\.|$chcom[0-9][0-9][0-9]\.|$chcom[0-9][0-9]\.|$chcom[0-9]\." ;;
#	http://boinc.fzk.de/poem/)
#        	limite="369s"
#		form="$chcom[0-3][0-6][0-9]\.|$chcom[0-9][0-9]\.|$chcom[0-9]\." ;;
#	http://www.worldcommunitygrid.org/)
#        	limite="59s"
#	        form="$chcom[0-5][0-9]\.|$chcom[0-9]\." ;;
#	http://www.cosmologyathome.org/)
#        	limite="1699s"
#		form="$chcom[1][0-6][0-9][0-9]\.|$chcom[0-9][0-9][0-9]\.|$chcom[0-9][0-9]\.|$chcom[0-9]\." ;;
#	http://einstein.phys.uwm.edu/)
#        	limite="669s"
#		form="$chcom[0-6][0-6][0-9]\.|$chcom[0-9][0-9]\.|$chcom[0-9]\." ;;
#	http://universeathome.pl/universe/)
#        	limite="1699s"
#		form="$chcom[1][0-6][0-9][0-9]\.|$chcom[0-9][0-9][0-9]\.|$chcom[0-9][0-9]\.|$chcom[0-9]\." ;;
#	*)
#		limite="99s"
#                form="$chcom[0-9][0-9]\.|$chcom[0-9]\." ;;
#esac

#Traitements
echo "En cours de surveillance... limite temps restant = $limite"
while true
do
	#Sélection des UT sur le point de se terminer
#	boinccmd --get_tasks | grep -n -B 19 -E "$form\." | grep -B 11 -A 8 "suspended via GUI: no" | grep -B 2 "$url_prj" | grep "   name: " | cut -d " " -f5 > /tmp/tasklist
	#list_time=($(boinccmd --get_tasks | grep -B 11 -A 8 "suspended via GUI: no" | grep -B 2 -A 17 "$url_prj" | grep -e "estimated" | grep -o '[0-9]*\.' | tr -d "."))
	list_done=($(boinccmd --get_tasks | grep -B 11 -A 8 "suspended via GUI: no" | grep -B 2 -A 17 "$url_prj" | grep -e "fraction done:"  | grep -o '[0-9]*\.[0-9]*'))
	#list_wu=($(boinccmd --get_tasks | grep -B 11 -A 8 "suspended via GUI: no" | grep -B 2 -A 17 "$url_prj" | grep "   name: " | cut -d " " -f5))
	list_wu=($(boinccmd --get_tasks | grep -B 11 -A 8 "suspended via GUI: no" | grep -B 2 -A 17 "$url_prj" | grep "   WU name: " | cut -d " " -f6))	
	counter=0
	for i in "${list_done[@]}"
	do
		#Suspensions
#		if [ ${list_time[$counter]} -le $limite ];then
		if [[ ${list_done[$counter]} > $limite ]];then
			#echo "${list_done[$counter]} -> ${list_wu[$counter]}"
#			echo "[`date "+%d%m%y %H:%M:%S"`] Suspension de : ${list_wu[$counter]} [temps restant = ${list_time[$counter]}s]"
			echo "[`date "+%d%m%y %H:%M:%S"`] Suspension de : ${list_wu[$counter]} [Portion effectuée = ${list_done[$counter]}]"
			cd $boincdos
			boinccmd --task "$url_prj" ${list_wu[$counter]} suspend
		fi
	counter=$((counter+1))
	done
	sleep 2
done

